#library "Levelup"
#include "zcommon.acs"

#define MaxLevel 60
int LevelNext[MaxLevel];


Script "Levelupcheck" (int EXPA)
{
GiveInventory("Expereince", EXPA);

int EXP = CheckInventory("Expereince");
int Lvl = CheckInventory("Playerlevel");
   
   if(EXP >= (100 * Lvl))
   {
      GiveInventory("Playerlevel", 1);
      TakeInventory("Expereince",(100 * lvl));
      ACS_NamedExecuteAlways("UpdateHealth",0);
	  ACS_NamedExecuteAlways("MaxAmmoScript",0);
   }

}